### ISSUE TITLE
Power Flow Card by Dante Winters

### ISSUE THREAD

**Issue by mfreudem** [zakery292/monitormysolar#11]
https://github.com/DanteWinters/lux-power-distribution-card

Some of the flow's aren't working on the latest release of the MonitorMySolar update.  

Example of the missing bits:
 - Undefined Home usage showing when using pload
 - Status showing as Unknown using state (could be my error).
 - Battery and other items don't show as the correct direction when charging or discharging etc.

[PowerFlowCard.txt](https://github.com/user-attachments/files/16828776/PowerFlowCard.txt)
[PowerFlowCard using Guys Codes.txt](https://github.com/user-attachments/files/16828781/PowerFlowCard.using.Guys.Codes.txt)
![image](https://github.com/user-attachments/assets/7794e02f-d27b-47c7-ae9f-44e557251fc2)

There is also another card I use - but this has LOTS of variables and lots now don't work. It was compatible with Guys codes - BUT not a major issue - prefer the Dante card anyway.

**Comment by zakery292** [comment]
Issue resolved in latest release
