### ISSUE TITLE
Weird behaviour when everything times

### ISSUE THREAD

**Issue by mfreudem** [zakery292/monitormysolar#21]
When entering times (on this occasion) in the "Force Discharge Start and Force Discharge End fields", upon refresh, the system has totally changed then. Couldn't understand why my system was exporting! Pics as examples attached

**Comment by mfreudem** [comment]
![Screenshot_20240910_082343_Home Assistant.jpg](https://github.com/user-attachments/assets/c9244c08-fe8e-46d2-a942-a5093c336e9c)

Screen shot with what I'd entered.

**Comment by mfreudem** [comment]
![Screenshot_20240910_082437_Home Assistant.jpg](https://github.com/user-attachments/assets/69f196cc-fd94-43af-bfaa-d698ff63f8af)

Screen shot with what it changed to.

**Comment by zakery292** [comment]
Will be fixed in next dongle firmware 1.3.1 and HA release

**Comment by zakery292** [comment]
fixed with release 1.2.0
