### ISSUE TITLE
Dongle seems to reset HA MQTT password

### ISSUE THREAD

**Issue by danielraffel** [zakery292/monitormysolar#30]
Twice in the past 24 hours, I noticed that HA stopped receiving MQTT data. On both occasions, when I checked the dongle HA enabled settings, the MQTT password field was empty. Previously, it was populated with **** and functioning correctly. In fact, after re-entering the password on the dongle it started working again (and subsequent visits to the dongle HA enabled settings showed **** in the password field indicating it was successfully set.) It seems something may be causing the password to get dropped. I’m currently running firmware version 2.0.6.

**Comment by zakery292** [comment]
Closing this now seems to be resolved with Dongle 2.0.32
