### ISSUE TITLE
HACS integration screenshots not loading

### ISSUE THREAD

**Issue by danielraffel** [zakery292/monitormysolar#33]
![image](https://github.com/user-attachments/assets/4d035a87-7d50-41bb-af34-6257002a7aa4)

**Comment by zakery292** [comment]
## Known issue
- Will update the readme.md and add the images to the repo to solve this. should be rectified over the weekend

**Comment by zakery292** [comment]
## Fixed
- Please reload the integration in home assistant (re download i think or update) when in the repo and they should now come through
