### ISSUE TITLE
Scan for networks doesn't seem to populate anything

### ISSUE THREAD

**Issue by danielraffel** [zakery292/monitormysolar#35]
![image](https://github.com/user-attachments/assets/e6476e7f-f888-41c4-af62-5638e7c6248e)

And WiFi password not shown in field as **

**Comment by zakery292** [comment]
## Known issue. 
- Will be fixed by dongle firmware 2.0.50 & UI firmware 2.0.30

**Comment by zakery292** [comment]
fixed in 2.2.0 FW and UI 2.0.60
