### ISSUE TITLE
[Dongle Feature] Show name of MQTT connector on Home Screen tooltip

### ISSUE THREAD

**Issue by danielraffel** [zakery292/monitormysolar#45]
### Feature Name

Show name of MQTT connector on Home Screen tooltip

### UI Or Firmware Feature?

UI

### Feature Description

Please show name of MQTT connector on Home Screen tooltip
Unclear what this is
![image](https://github.com/user-attachments/assets/c703f979-b303-4287-b137-f817e003546d)

also, on safari in macOS I can't see these
<img width="557" alt="image" src="https://github.com/user-attachments/assets/a838be5d-e433-4d43-aeb8-360b4d91970a">

### Usage Scenarios

knowing what the icon is referencing and seeing them on desktop

### Current Firmware Version

2.1.4/2.0.57

**Comment by zakery292** [comment]
Fixed in UI 2.0.60
