### ISSUE TITLE
[BUG] Too much logging

### ISSUE THREAD

**Issue by skrul** [zakery292/monitormysolar#56]
### Affected Component

Home Assistant

### Version Information

1.3.2

### Media Attachments

<img width="925" alt="IMG_3016" src="https://github.com/user-attachments/assets/cdbc4fc3-f448-4281-aa9e-27c1da91c017" />

### MQTT Output

```shell
n/a
```

### Detailed Description

The WARNING logs are very frequent and flooding my HAOS system logs. I have > 200MB of logs that only contain 8 seconds of logs :sad

### Issues

- [X] I agree i have checked the Issues Tab to see if this already Exists

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zakery292** [comment]
Fixed in 1.4.4
